import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Navigate } from '@ngxs/router-plugin';
import { Store } from '@ngxs/store';
import { ModelMapping } from '@xbim/flex-api';
import { AddExpands, Expand, SetActive } from '@xbim/flex-webkit';
import { GridColumnDefinition } from '@xbim/grid';
import { NGXLogger } from 'ngx-logger';
import { CommonEntityColumns, DateCreatedColumns } from 'src/app/common-columns';
import { ModelMappingService } from '../state/diff-service.providers';
import { ModelMappingState } from '../state/diffs-state';
import { ModelMappingComparer } from './diff-comparer';

@Component({
  selector: 'app-diff-list',
  templateUrl: './diff-list.component.html',
  styleUrls: ['./diff-list.component.scss']
})
export class DiffListComponent implements OnInit {

  constructor(
    private store: Store,
    private route: ActivatedRoute,
    private logger: NGXLogger) { }

  definedColumns: GridColumnDefinition[] = [
    {
      id: 'MappingId',
      title: 'ID',

    },
    {
      id: 'CreatedBy',
      title: 'Generated By',
      fieldType: 'Reference',
      field: 'Name',

    },
    {
      id: 'SourceAssetModel',
      title: 'Original Model',
      fieldType: 'Reference',
      field: 'Name',
      orderbyField: 'SourceAssetModel/Name'
    },
    {
      id: 'TargetAssetModel',
      title: 'New Model',
      fieldType: 'Reference',
      field: 'Name',
      orderbyField: 'TargetAssetModel/Name',
      isPrimary: true,
      selectAction: (row, _) => this.openDiff(row)
    },
    {
      id: 'Mapped',
      title: '# Mapped',
      fieldType: 'Badge',
      field: 'MappedEntities@odata.count',
      orderbyField: 'MappedEntities/$count',
      badgeIcon: 'check_circle_outline'
    },
    {
      id: 'Lost',
      title: '# Lost',
      fieldType: 'Badge',
      field: 'LostEntities@odata.count',
      orderbyField: 'LostEntities/$count',
      badgeIcon: 'remove_circle_outline'
    },
    {
      id: 'Found',
      title: '# Found',
      fieldType: 'Badge',
      field: 'FoundEntities@odata.count',
      orderbyField: 'FoundEntities/$count',
      badgeIcon: 'add_circle_outline'
    },
    {
      id: 'MatchCandidates',
      title: '# Possible Matches',
      fieldType: 'Badge',
      field: 'CandidateMatches@odata.count',
      orderbyField: 'CandidateMatches/$count',
      badgeIcon: 'help_outline'
    },
    ...DateCreatedColumns
  ];

  orderedColumns = ['TargetAssetModel', 'SourceAssetModel', 'Mapped', 'Lost', 'Found', 'CreatedBy', 'DateCreated',];
  public stateType = ModelMappingState;
  public comparer = new ModelMappingComparer();

  ngOnInit(): void {
    this.store.dispatch(new AddExpands(ModelMappingState, [
      new Expand('SourceAssetModel'),
      new Expand('TargetAssetModel'),
      new Expand('CreatedBy'),
      new Expand('MappedEntities', '$count=true;$top=0'),
      new Expand('LostEntities', '$count=true;$top=0'),
      new Expand('FoundEntities', '$count=true;$top=0'),
      new Expand('CandidateMatches', '$count=true;$top=0'),
    ]));
  }

  openDiff(row: ModelMapping) {
    this.logger.debug('Navigate to ', row);
    this.store.dispatch([
      //new SetActive(ModelMappingState, row.MappingId),
      new Navigate([row.MappingId, 'detail'], null, { relativeTo: this.route })
    ]);
  }

}
